Feature task one
PivkinAlex/ToDoApp pull request #1
Opened 2022-03-27 15:55 UTC by PivkinAlex

2022-03-28 07:36 UTC, Alexandr-Prokin requested changes
Не правильно импортировал картинки, у тебя в проекте ошибка.
Круги при импорте срезал
Посмотри, где в текст инпутах начинается подсказка, нужно сдвинуть (padding)

2022-03-28 07:36 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +            android:fontFamily="@font/poppins" />
если удалить шрифт тот же останется?

2022-03-28 07:36 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="325dp"
размеры

2022-03-28 07:36 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/button3"
именование кнопки должно быть другое

2022-03-28 07:36 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="190dp"
размеры

2022-03-28 07:36 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="314dp"
размеры

2022-03-28 07:36 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/button4"
id нужно переименовать, посмотри руководство по именованию

2022-03-28 07:36 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +
пустую строку удалить

2022-03-28 07:36 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="220dp"
размеры

2022-03-28 07:36 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/textView"
переименовать

2022-03-28 07:36 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/button2"
именование

2022-03-28 07:36 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="120dp"
размеры

2022-04-05 19:06 UTC, Alexandr-Prokin requested changes
Картинки нужно было конверитировать в png, но можешь так оставить пока.

2022-04-05 19:06 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:background=""
если параметра нету, зачем он тогда?

2022-04-05 19:06 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginEnd="202dp"
убери этот параметр

2022-04-05 19:06 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintEnd_toEndOf="parent"
и этот, теперь должно быть все ровно (круги убежали)

2022-04-07 18:23 UTC, PivkinAlex commented
я исправил. еще уменьшил некоторые размеры, так как на экран моего телефона оно не влезало

2022-04-07 19:41 UTC, Alexandr-Prokin requested changes
Элементы экрана должны прикрепляться друг за другом, у тебя  кто к чему прикреплен. 
У каждого замечания есть кнопка resolve, когда правка исправлена, нужно нажимать эту кнопку. У тебя сейчас куча замечаний висит, как будто не исправлял

2022-04-07 19:41 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +    <Button
Меняй на TextView

2022-04-07 19:41 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="190dp"
точных размеров не должно быть, через argin регулируй размеры

2022-04-07 19:41 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="76dp"
точных размеров не должно

2022-04-07 19:41 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="50dp"
опять размеры

2022-04-07 19:41 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +    <Button
Меняй на TextView

2022-04-07 19:41 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginEnd="202dp"
Это зачем?

2022-04-07 19:41 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="188dp"
опять размеры точные

2022-04-07 22:12 UTC, PivkinAlex commented
Исправил, надеюсь это последний раз)

2022-04-08 06:52 UTC, Alexandr-Prokin requested changes
Точные размеры не задаются в адаптивной верстке, 0 - это тоже точный размер, как и любое число.
Остальные экраны с учетом этих замечаний должны быть реализованы. Но пока с этим надо разобраться

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="0dp"
wrap content - размер по содержимому, нужно этот параметр ставить

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginEnd="202dp"
это удалить

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintEnd_toEndOf="parent"
это удалить

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        app:srcCompat="@drawable/top" />
картинку с кругами назвать "top" как то не правильно

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
размер по содежимому должен

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:gravity="center"
можно без него обойтись

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginLeft="25dp"
marginHorizontal установит и с лева и с права отступы

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="0dp"
тут тоже не верно

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintTop_toBottomOf="@+id/imageFilterView7" />
к верху контейнера нужно, а не к кругам

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/editEmail"
название не понятное, должно заканчиваться на Layout

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/emailInput"
тут тоже с названием проблемы

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="0dp"
с размерами проблемы

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/editPassword"
название не верное

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="0dp"
размеры

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/passwordInput"
название

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="0dp"
опять размеры

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:gravity="center"
это не нужно

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/SignInButton"
стиль именования не верный, прочитай руководство именования

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="0dp"
опять размеры

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:gravity="center"
это лишнее

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="0dp"
размеры

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="0dp"
размеры

2022-04-08 06:52 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_main.xml
> +        android:gravity="center"
это убрать

2022-04-08 18:03 UTC, PivkinAlex commented
Исправил

2022-04-08 19:48 UTC, Alexandr-Prokin approved these changes
Есть конечно еще не доработки, пока пойдет

2022-04-08 19:49 UTC, merged