Feature task two
PivkinAlex/ToDoApp pull request #2
Opened 2022-04-09 21:33 UTC by PivkinAlex

2022-04-10 09:15 UTC, Alexandr-Prokin requested changes
Где есть bias, везде все удаляешь, делаешь без биасов.
Так же нужно решить конфликт при слиянии

2022-04-10 09:15 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_registration.xml
> +        app:layout_constraintEnd_toEndOf="parent"
К верху и левой части прикрепляется

2022-04-10 09:15 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_registration.xml
> +        app:layout_constraintHorizontal_bias="0.0"
удалить

2022-04-10 09:15 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_registration.xml
> +        android:textAlignment="center"
если удалить что нибудь изениться?

2022-04-10 09:15 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_registration.xml
> +        app:layout_constraintHorizontal_bias="0.547"
удалить

2022-04-10 09:15 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_registration.xml
> +        app:layout_constraintLeft_toLeftOf="parent"
к textView0 привязывается

2022-04-10 09:15 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_registration.xml
> +        app:layout_constraintEnd_toEndOf="parent"
к textView2 привязывается

2022-04-10 09:15 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_registration.xml
> +        app:layout_constraintHorizontal_bias="0.5"
удалить

2022-04-10 09:15 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_registration.xml
> +        app:layout_constraintEnd_toEndOf="parent"
к элементу который выше, нужно привязать

2022-04-10 09:15 UTC, Alexandr-Prokin commented on app/src/main/res/layout/activity_splash_screen.xml
> +        android:id="@+id/getStartedbutton"
именование не верное

2022-04-12 13:47 UTC, PivkinAlex commented
Конфликты решил

2022-04-12 13:52 UTC, PivkinAlex commented
насчет приглашения в ваш проект(я его не нашел), там скорее всего приглашение просрочилось, его надо по-новой прислать

2022-04-13 18:10 UTC, PivkinAlex commented
изменил, сделал вроде как надо

2022-04-14 07:40 UTC, Alexandr-Prokin approved these changes
Молодец, хорошо сделал

2022-04-14 07:41 UTC, merged